// AUTO-GENERATED — NE PAS MODIFIER MANUELLEMENT
// Genere par scripts/sync-client.ts depuis CLIENT.md
// Pour modifier: editer CLIENT.md puis lancer npm run sync-client

export const clientConfig = {
  NOM_ENTREPRISE: "Hoffmann Rene-Georges",
  NOM_LEGAL: "Hoffmann Rene-Georges",
  SIRET: "993 691 278",
  METIER: "couvreur",
  METIER_LABEL: "Couvreur",
  GENRE_DIRIGEANT: "M",
  PRENOM_DIRIGEANT: "René-Georges",
  NOM_DIRIGEANT: "Hoffmann",
  DIPLOME_DIRIGEANT: "couvreur-zingueur diplome, compagnon du devoir",
  ANNEE_CREATION: "2025",
  ANNEES_EXPERIENCE: "15",
  TELEPHONE: "06 72 10 28 29",
  EMAIL: "contact@hoffmann-couvreur.fr",
  ADRESSE: "317 Rue de la Garenne",
  CODE_POSTAL: "92000",
  VILLE: "Nanterre",
  DEPARTEMENT: "Hauts-de-Seine",
  REGION: "Île-de-France",
  PAYS: "France",
  HORAIRES: "Lun-Ven: 8h00-18h00, Sam: 9h00-13h00",
  ZONE_INTERVENTION: "Nanterre et région Île-de-France",
  ZONES_LISTE: "Nanterre, Puteaux, La Défense, Courbevoie, Levallois-Perret, Rueil-Malmaison, Neuilly-sur-Seine, Boulogne-Billancourt",
  LATITUDE: "48.8975",
  LONGITUDE: "2.2048",
  COULEUR_PRIMAIRE_HUE: "220",
  COULEUR_PRIMAIRE_900: "oklch(0.22 0.06 220)",
  COULEUR_ACCENT_HUE: "25",
  COULEUR_ACCENT_500: "oklch(0.64 0.16 25)",
  COULEUR_FOND_50: "oklch(0.985 0.005 80)",
  FONT_TITRES: "Playfair Display",
  FONT_CORPS: "DM Sans",
  DOMAINE: "www.hoffmann-couvreur.fr",
  META_TITLE: "Hoffmann Rene-Georges | Couvreur a Nanterre",
  META_DESCRIPTION: "Couvreur a Nanterre (92000). Couverture neuve, renovation de toiture, zinguerie, isolation, depannage urgent. Devis gratuit. Intervention Île-de-France.",
  META_KEYWORDS: "couvreur Nanterre, couverture Nanterre, toiture Nanterre, renovation toiture Hauts-de-Seine, zinguerie, isolation toiture, depannage toiture urgent, couvreur professionnel",
  SCHEMA_TYPE: "RoofingContractor",
  SLOGAN: "Votre Toiture, Notre Métier",
  ACCROCHE_HERO: "Votre Toiture — Entre de Bonnes Mains",
  DESCRIPTION_ENTREPRISE: "Hoffmann Rene-Georges, artisan couvreur professionnel basé à Nanterre. Couverture, renovation, zinguerie et isolation — un savoir-faire artisanal au service de votre toiture depuis 2025.",
  DESCRIPTION_FOOTER: "Couvreur professionnel à Nanterre spécialisé en rénovation de toitures, couverture neuve et zinguerie en Île-de-France.",
  DESCRIPTION_APROPOS: "Fondee par René-Georges Hoffmann, notre entreprise est nee d'une passion profonde pour les metiers de la couverture et du batiment. Avec 15 ans d'experience, nous mettons notre expertise au service de la qualite et de la durabilite de vos projets.",
  SERVICE_1_TITRE: "Couverture Neuve",
  SERVICE_1_DESC: "Installation complete de votre toiture en ardoise, tuile ou zinc, avec une finition soignee et durable.",
  SERVICE_2_TITRE: "Renovation de Toiture",
  SERVICE_2_DESC: "Refection partielle ou totale de votre couverture pour redonner etancheite et esthetique a votre toit.",
  SERVICE_3_TITRE: "Zinguerie",
  SERVICE_3_DESC: "Pose et reparation de gouttieres, descentes EP, cheneaux, noues et abergements en zinc ou cuivre.",
  SERVICE_4_TITRE: "Isolation de Toiture",
  SERVICE_4_DESC: "Isolation thermique par l'interieur ou l'exterieur (sarking) pour ameliorer le confort et reduire la facture energetique.",
  SERVICE_5_TITRE: "Depannage & Urgence",
  SERVICE_5_DESC: "Intervention rapide pour fuites, tuiles cassees, bachage d'urgence et reparations suite a intemperies.",
  SERVICE_6_TITRE: "Demoussage & Entretien",
  SERVICE_6_DESC: "Nettoyage, traitement anti-mousse et hydrofuge pour prolonger la duree de vie de votre toiture.",
  GOOGLE_MAPS_URL: "",
  GOOGLE_REVIEWS_URL: "",
  FACEBOOK_URL: "",
  INSTAGRAM_URL: "",
  LINKEDIN_URL: "",
  PINTEREST_URL: "",
  TEMOIGNAGE_1_NOM: "Client Satisfait",
  TEMOIGNAGE_1_VILLE: "Votre Ville",
  TEMOIGNAGE_1_TEXTE: "Nom de l'Entreprise a refait entierement notre toiture en ardoise. Le travail est impeccable, l'equipe ponctuelle et soigneuse. Nous recommandons les yeux fermes !",
  TEMOIGNAGE_1_NOTE: "5",
  TEMOIGNAGE_2_NOM: "Famille Placeholder",
  TEMOIGNAGE_2_VILLE: "Commune voisine",
  TEMOIGNAGE_2_TEXTE: "Intervention rapide apres une fuite. Diagnostic precis, reparation efficace et prix honnete. Un vrai professionnel de la couverture.",
  TEMOIGNAGE_2_NOTE: "5",
  TEMOIGNAGE_3_NOM: "M. Placeholder",
  TEMOIGNAGE_3_VILLE: "Ville proche",
  TEMOIGNAGE_3_TEXTE: "Renovation complete de notre zinguerie. Gouttieres en zinc posees avec un soin remarquable. Aucun probleme depuis, meme apres de fortes pluies.",
  TEMOIGNAGE_3_NOTE: "5",
  HEBERGEUR_NOM: "Vercel Inc.",
  HEBERGEUR_ADRESSE: "340 Pine Street, Suite 701, San Francisco, CA 94104, USA",
  HEBERGEUR_SITE: "vercel.com",
  N8N_WEBHOOK: "",
  ADMIN_PASSWORD: "1234",
  PACK_PHOTOS_METIER: "couvreur",
} as const;

export type ClientConfigKey = keyof typeof clientConfig;
